import type { Metadata } from "next";
import localFont from "next/font/local";

import DashboardWrapper from "./dashboardWrapper";
import { Inter } from "next/font/google";

import { PrimeReactProvider } from 'primereact/api';

import 'primeicons/primeicons.css';

import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
       // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={inter.className}
      >
        <PrimeReactProvider value={{ unstyled: false }}>
          <DashboardWrapper>{children}</DashboardWrapper>
        </PrimeReactProvider>
      </body>
    </html>
  );
}
